package AdivinaAdivinador.Preguntas;

public enum TiposDePregunta {
    GENERO, GENERO_MUJER, CALVO, LENTES, PELO_RUBIO, PELO_ROJO, PELO_NEGRO, PELO_MARRON, BARBA, REMERA_BLANCA, REMERA_ROJA, REMERA_AZUL, REMERA_VERDE, REMERA_AMARILLA, REMERA_LILA, GORRO
}